Wwwision:
  Eventr:
    eventHandlers:
      preprocess:
        'addAggregateIdToMetadata':
          handlerClassName: 'Wwwision\Eventr\EventHandler\AddAggregateIdToMetadataEventHandler'
        'addDateToMetadata':
          handlerClassName: 'Wwwision\Eventr\EventHandler\AddDateToMetadataEventHandler'
        'verifyPayload':
          position: 'end'
          handlerClassName: 'Wwwision\Eventr\EventHandler\VerifyPayloadEventHandler'
      postprocess:
        'synchronousProjections':
          handlerClassName: 'Wwwision\Eventr\EventHandler\SynchronousProjectionEventHandler'
        'asynchronousProjections':
          handlerClassName: 'Wwwision\Eventr\EventHandler\AsynchronousProjectionEventHandler'
Flowpack:
  Jobqueue:
    Common:
      queues:
        'eventr-projection':
          className: 'TYPO3\Jobqueue\Beanstalkd\Queue\BeanstalkdQueue'